{{/*
MediaStation — PersistentVolumeClaim for Data
*/}}
{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mediastation.dataPVC" . }}
  labels:
    {{- include "mediastation.labels" . | nindent 4 }}
    app.kubernetes.io/component: data
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | default "ReadWriteOnce" }}
  {{- if .Values.persistence.storageClass }}
  {{- if not (eq "" .Values.persistence.storageClass) }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
